USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS NIKOLAY_BOGDANOV;

USE DATABASE NIKOLAY_BOGDANOV;

CREATE WAREHOUSE IF NOT EXISTS DEPLOYMENT_WH
WITH WAREHOUSE_SIZE='X-SMALL'
     MAX_CLUSTER_COUNT = 1
     MIN_CLUSTER_COUNT = 1
     ;

USE WAREHOUSE DEPLOYMENT_WH;

CREATE WAREHOUSE IF NOT EXISTS TASKS_WH
WITH WAREHOUSE_SIZE='X-SMALL'
     MAX_CLUSTER_COUNT = 1
     MIN_CLUSTER_COUNT = 1
     ;

CREATE SCHEMA NIKOLAY_BOGDANOV.STAGING;
CREATE SCHEMA NIKOLAY_BOGDANOV.STORAGE;
CREATE SCHEMA NIKOLAY_BOGDANOV.DATA_MARTS;

USE NIKOLAY_BOGDANOV.STAGING;

create stage SF_stage
  url='s3://de-school-snowflake/'
  credentials=(aws_key_id='<aws_key_id here>' aws_secret_key='<aws_secret_key here>');